name: CI

on:
    push:
      branches: ["main"]
    pull_request:
      branches: ["*"]
    workflow_dispatch:

# Cancel in-progress runs when a new workflow with the same group is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    basic-python-checks:
      name: Basic Python Checks
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v6
            with:
              lfs: false # only user guide has lfs objects

          - uses: actions/checkout@v6

          - uses: astral-sh/ruff-action@v3

          - name: Check code formatting
            working-directory: python
            run: ruff format --diff

          - name: Lint code base
            working-directory: python
            run: ruff check

    basic-rust-checks:
      name: Basic Rust Checks
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v6
            with:
              lfs: false # only user guide has lfs objects

          # https://github.com/Algebraic-UG/squishy_volumes/issues/``309
          #- uses: dtolnay/rust-toolchain@stable
          - uses: dtolnay/rust-toolchain@nightly
            with:
              targets: ${{ inputs.target-triple }}
              components: clippy, rustfmt

          - working-directory: rust
            run: cargo fmt --check

          - working-directory: rust
            run: cargo clippy --all-targets
